name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

# This config is vaguely based on https://github.com/futurice/myRetroGenerator/blob/master/.github/workflows/ci.yml

# ubuntu-latest comes with GHC 9.8.1 and Stack 2.13.1 as of 16 Dec 2023.
# https://github.com/commercialhaskell/stack/blob/master/.github/workflows/unit-tests.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('closet.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        stack update
        stack build --only-dependencies
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
